### ISSUE TITLE
Change references to 'ember-template' throughout the application

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/ember-routing#10]
`ember-routing-static`

**Comment by laurenfazah** [comment]
@jrhorn424 should be good if you want to close

**Comment by jrhorn424** [comment]
**All** names should be `ga-wdi-boston.ember-routing-static`. No slashes. Must prefix.

Except for the page title, of course.

**Comment by berziiii** [comment]
Resolved in 2ce8c26

**Comment by raq929** [comment]
I have double check that this is resolved.
